# Generated by Django 3.2.4 on 2021-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=10)),
                ('userName', models.CharField(max_length=15)),
                ('userID', models.CharField(max_length=20, unique=True)),
                ('userpassword', models.CharField(max_length=20)),
                ('feedimage', models.ImageField(blank=True, upload_to='feed.html')),
                ('feedtext', models.TextField(blank=True)),
                ('profileimage', models.ImageField(blank=True, upload_to='profile.html')),
                ('created_db', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
